---
- name: install tomcat
  hosts: tomcat
  become: yes

  tasks:
  - name: Ensure tomcat package is present
    apt:
     update_cache: yes
     name: tomcat8
     state: present
  

- name: install maven
  hosts: maven
  become: yes

  tasks:
  - name: Ensure maven package is present
    apt:
     name: maven
     state: latest

  - name: Ensure dir for git is there
    file: 
     path: /home/gitclone
     state: directory

  - name: Ensure app clone from git   
    git: 
     repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
     dest: /home/gitclone
     clone: yes

  - name: Ensure app is package
    shell: mvn package
    args:
     chdir: /home/gitclone
  
  - name: Copy war in host with tomcat
    shell: rsync -avz /home/gitclone/target/hello-1.0.war root@34.125.251.177/var/lib/tomcat8/webapps

  #- name: Copy war in host with tomcat
  #  synchronize: 
  #   src: /home/gitclone/target/hello-1.0.war
  #   dest: rsync://root@34.125.251.177/var/lib/tomcat8/webapps

- name: restart tomcat
  hosts: tomcat
  become: yes

  tasks:
  - name: restart tomcat8
    service :
     name: tomcat
     state: restarted